#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TEGAAndroid.Resource", IsApplication=true)]

namespace TEGAAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int vehicleType = 2131099648;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int docStopGreen = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int gefahrgutRed = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int green = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int greyLight = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int logiBlue = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int secondGreen = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int transparent = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int transparentBlack = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int transparentGrey = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Anonymous_Male = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int awards = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int badge = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int badge1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int badge1Locked = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int border = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int car = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int close = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int copyright = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dark_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dark_background_monochrom = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int emotion = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int facebook_icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int friends = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int headerLine = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int history = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int home = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int hometotalicon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int humance = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Info_page_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int leaderboard = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int levelUp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int light_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int light_background_monochrom = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int login = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int login_button = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int login_down = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int logout = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int logout_button = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int logout_down = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int MainPage = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Menu = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int menuBackground = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int mercedes = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pointicon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int profile = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int profpic = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int register_new = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int settingsGrey = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int splash = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Splashscreen = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int stars = 2130837546;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080022
			public const int ImageViewhome = 2131230754;
			
			// aapt resource value: 0x7f08002a
			public const int ImageViewhomeProfPic = 2131230762;
			
			// aapt resource value: 0x7f080094
			public const int LinearLayoutBadge = 2131230868;
			
			// aapt resource value: 0x7f08008a
			public const int LinearLayoutBirthDate = 2131230858;
			
			// aapt resource value: 0x7f08008d
			public const int LinearLayoutDrivingCar = 2131230861;
			
			// aapt resource value: 0x7f080090
			public const int LinearLayoutEfficiency = 2131230864;
			
			// aapt resource value: 0x7f080096
			public const int LinearLayoutEmotion = 2131230870;
			
			// aapt resource value: 0x7f080086
			public const int LinearLayoutPersDataContent = 2131230854;
			
			// aapt resource value: 0x7f080088
			public const int LinearLayoutProfDetails = 2131230856;
			
			// aapt resource value: 0x7f080092
			public const int LinearLayoutStatus = 2131230866;
			
			// aapt resource value: 0x7f080028
			public const int RelativeLayoutHome = 2131230760;
			
			// aapt resource value: 0x7f08006b
			public const int baseLayout = 2131230827;
			
			// aapt resource value: 0x7f0800a6
			public const int birthDate = 2131230886;
			
			// aapt resource value: 0x7f0800ab
			public const int btnImageUpload = 2131230891;
			
			// aapt resource value: 0x7f0800ac
			public const int btnRegister = 2131230892;
			
			// aapt resource value: 0x7f080078
			public const int buttonAwards = 2131230840;
			
			// aapt resource value: 0x7f080073
			public const int buttonCar = 2131230835;
			
			// aapt resource value: 0x7f080076
			public const int buttonFriends = 2131230838;
			
			// aapt resource value: 0x7f08007e
			public const int buttonHistory = 2131230846;
			
			// aapt resource value: 0x7f08006e
			public const int buttonHome = 2131230830;
			
			// aapt resource value: 0x7f08007b
			public const int buttonLeaderboard = 2131230843;
			
			// aapt resource value: 0x7f080084
			public const int buttonLogout = 2131230852;
			
			// aapt resource value: 0x7f080006
			public const int buttonMenu = 2131230726;
			
			// aapt resource value: 0x7f080071
			public const int buttonProfile = 2131230833;
			
			// aapt resource value: 0x7f080081
			public const int buttonSettings = 2131230849;
			
			// aapt resource value: 0x7f0800a7
			public const int carContent = 2131230887;
			
			// aapt resource value: 0x7f0800aa
			public const int carImageView = 2131230890;
			
			// aapt resource value: 0x7f0800a0
			public const int email = 2131230880;
			
			// aapt resource value: 0x7f08006a
			public const int footer = 2131230826;
			
			// aapt resource value: 0x7f080063
			public const int header = 2131230819;
			
			// aapt resource value: 0x7f080041
			public const int imageView1 = 2131230785;
			
			// aapt resource value: 0x7f08000b
			public const int imageView2 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int imageView3 = 2131230732;
			
			// aapt resource value: 0x7f080057
			public const int imageView4 = 2131230807;
			
			// aapt resource value: 0x7f08005f
			public const int imageView5 = 2131230815;
			
			// aapt resource value: 0x7f080095
			public const int imageViewBadge = 2131230869;
			
			// aapt resource value: 0x7f080015
			public const int imageViewCar = 2131230741;
			
			// aapt resource value: 0x7f080097
			public const int imageViewEmotion = 2131230871;
			
			// aapt resource value: 0x7f080004
			public const int imageViewHeader = 2131230724;
			
			// aapt resource value: 0x7f080026
			public const int imageViewLatestBadge1 = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int imageViewLatestBadge2 = 2131230759;
			
			// aapt resource value: 0x7f08003e
			public const int imageViewLeadPic1 = 2131230782;
			
			// aapt resource value: 0x7f080046
			public const int imageViewLeadPic2 = 2131230790;
			
			// aapt resource value: 0x7f08004d
			public const int imageViewLeadPic3 = 2131230797;
			
			// aapt resource value: 0x7f080054
			public const int imageViewLeadPic4 = 2131230804;
			
			// aapt resource value: 0x7f08005c
			public const int imageViewLeadPic5 = 2131230812;
			
			// aapt resource value: 0x7f080037
			public const int imageViewLevelIcon = 2131230775;
			
			// aapt resource value: 0x7f080034
			public const int imageViewPointIcon = 2131230772;
			
			// aapt resource value: 0x7f080087
			public const int imageViewProfile = 2131230855;
			
			// aapt resource value: 0x7f080033
			public const int imageViewTotalIcon = 2131230771;
			
			// aapt resource value: 0x7f08009d
			public const int lastName = 2131230877;
			
			// aapt resource value: 0x7f080002
			public const int linearLayoutAwards = 2131230722;
			
			// aapt resource value: 0x7f080012
			public const int linearLayoutCar = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int linearLayoutCarContent = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int linearLayoutCarInfo = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int linearLayoutCarInfoTablet = 2131230746;
			
			// aapt resource value: 0x7f080014
			public const int linearLayoutCarTitle = 2131230740;
			
			// aapt resource value: 0x7f080023
			public const int linearLayoutEfficiency = 2131230755;
			
			// aapt resource value: 0x7f080075
			public const int linearLayoutFrieds = 2131230837;
			
			// aapt resource value: 0x7f080021
			public const int linearLayoutGreeting = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int linearLayoutHeader = 2131230752;
			
			// aapt resource value: 0x7f08007d
			public const int linearLayoutHistory = 2131230845;
			
			// aapt resource value: 0x7f08001f
			public const int linearLayoutHome = 2131230751;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayoutLatestAwards = 2131230730;
			
			// aapt resource value: 0x7f08003a
			public const int linearLayoutLeaderBoard = 2131230778;
			
			// aapt resource value: 0x7f08007a
			public const int linearLayoutLeaderboard = 2131230842;
			
			// aapt resource value: 0x7f080062
			public const int linearLayoutLogin = 2131230818;
			
			// aapt resource value: 0x7f080083
			public const int linearLayoutLogout = 2131230851;
			
			// aapt resource value: 0x7f08006d
			public const int linearLayoutMenu = 2131230829;
			
			// aapt resource value: 0x7f080070
			public const int linearLayoutProfile = 2131230832;
			
			// aapt resource value: 0x7f080099
			public const int linearLayoutRegister = 2131230873;
			
			// aapt resource value: 0x7f080080
			public const int linearLayoutSettings = 2131230848;
			
			// aapt resource value: 0x7f0800ad
			public const int link_to_login = 2131230893;
			
			// aapt resource value: 0x7f080069
			public const int link_to_register = 2131230825;
			
			// aapt resource value: 0x7f080066
			public const int logInBtn = 2131230822;
			
			// aapt resource value: 0x7f080068
			public const int login = 2131230824;
			
			// aapt resource value: 0x7f080064
			public const int loginEditTxt = 2131230820;
			
			// aapt resource value: 0x7f08009a
			public const int menuButton = 2131230874;
			
			// aapt resource value: 0x7f08009c
			public const int name = 2131230876;
			
			// aapt resource value: 0x7f08009b
			public const int pageContent = 2131230875;
			
			// aapt resource value: 0x7f0800a1
			public const int password = 2131230881;
			
			// aapt resource value: 0x7f080065
			public const int passwordEditTxt = 2131230821;
			
			// aapt resource value: 0x7f0800a2
			public const int passwordRetype = 2131230882;
			
			// aapt resource value: 0x7f0800a9
			public const int plateNumber = 2131230889;
			
			// aapt resource value: 0x7f0800a5
			public const int radioFemale = 2131230885;
			
			// aapt resource value: 0x7f0800a4
			public const int radioMale = 2131230884;
			
			// aapt resource value: 0x7f0800a3
			public const int radioSex = 2131230883;
			
			// aapt resource value: 0x7f080091
			public const int ratingBar1 = 2131230865;
			
			// aapt resource value: 0x7f080025
			public const int ratingBarEfficiency = 2131230757;
			
			// aapt resource value: 0x7f08001d
			public const int relativeLayout1 = 2131230749;
			
			// aapt resource value: 0x7f080007
			public const int relativeLayoutAwardsContent = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int relativeLayoutAwardsNewBadges = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayoutCar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int relativeLayoutHeader = 2131230723;
			
			// aapt resource value: 0x7f080029
			public const int relativeLayoutHomeContent = 2131230761;
			
			// aapt resource value: 0x7f08003c
			public const int relativeLayoutLeaderboard1 = 2131230780;
			
			// aapt resource value: 0x7f080044
			public const int relativeLayoutLeaderboard2 = 2131230788;
			
			// aapt resource value: 0x7f08004b
			public const int relativeLayoutLeaderboard3 = 2131230795;
			
			// aapt resource value: 0x7f080052
			public const int relativeLayoutLeaderboard4 = 2131230802;
			
			// aapt resource value: 0x7f08005a
			public const int relativeLayoutLeaderboard5 = 2131230810;
			
			// aapt resource value: 0x7f08003b
			public const int relativeLayoutLeaderboardContent = 2131230779;
			
			// aapt resource value: 0x7f08000f
			public const int relativeLayoutNewAwards = 2131230735;
			
			// aapt resource value: 0x7f08006c
			public const int scrollMeny = 2131230828;
			
			// aapt resource value: 0x7f080009
			public const int scrollView1 = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int scrollView2 = 2131230734;
			
			// aapt resource value: 0x7f080001
			public const int scrollViewCar = 2131230721;
			
			// aapt resource value: 0x7f08001e
			public const int scrollViewHome = 2131230750;
			
			// aapt resource value: 0x7f080039
			public const int scrollViewLeaderBoard = 2131230777;
			
			// aapt resource value: 0x7f080008
			public const int textView1 = 2131230728;
			
			// aapt resource value: 0x7f080011
			public const int textView2 = 2131230737;
			
			// aapt resource value: 0x7f080019
			public const int textViewAvgConsResult = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int textViewAvgConsum = 2131230744;
			
			// aapt resource value: 0x7f080079
			public const int textViewAwards = 2131230841;
			
			// aapt resource value: 0x7f08008b
			public const int textViewBirthDate = 2131230859;
			
			// aapt resource value: 0x7f08008c
			public const int textViewBirthDateVal = 2131230860;
			
			// aapt resource value: 0x7f080074
			public const int textViewCar = 2131230836;
			
			// aapt resource value: 0x7f080016
			public const int textViewCarType = 2131230742;
			
			// aapt resource value: 0x7f08008e
			public const int textViewDrives = 2131230862;
			
			// aapt resource value: 0x7f08008f
			public const int textViewDrivesVal = 2131230863;
			
			// aapt resource value: 0x7f080024
			public const int textViewEfficiency = 2131230756;
			
			// aapt resource value: 0x7f080077
			public const int textViewFriends = 2131230839;
			
			// aapt resource value: 0x7f08007f
			public const int textViewHistory = 2131230847;
			
			// aapt resource value: 0x7f08006f
			public const int textViewHome = 2131230831;
			
			// aapt resource value: 0x7f080035
			public const int textViewHomeEarnedName = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int textViewHomeEarnedPoints = 2131230774;
			
			// aapt resource value: 0x7f080038
			public const int textViewHomeLevelStatus = 2131230776;
			
			// aapt resource value: 0x7f080031
			public const int textViewHomeName = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int textViewHomePoints = 2131230770;
			
			// aapt resource value: 0x7f08002f
			public const int textViewHours = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int textViewHoursVal = 2131230768;
			
			// aapt resource value: 0x7f08002b
			public const int textViewKilometer = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int textViewKilometerVal = 2131230764;
			
			// aapt resource value: 0x7f080043
			public const int textViewLeadDistance1 = 2131230787;
			
			// aapt resource value: 0x7f08004a
			public const int textViewLeadDistance2 = 2131230794;
			
			// aapt resource value: 0x7f080051
			public const int textViewLeadDistance3 = 2131230801;
			
			// aapt resource value: 0x7f080059
			public const int textViewLeadDistance4 = 2131230809;
			
			// aapt resource value: 0x7f080061
			public const int textViewLeadDistance5 = 2131230817;
			
			// aapt resource value: 0x7f080042
			public const int textViewLeadFuel1 = 2131230786;
			
			// aapt resource value: 0x7f080049
			public const int textViewLeadFuel2 = 2131230793;
			
			// aapt resource value: 0x7f080050
			public const int textViewLeadFuel3 = 2131230800;
			
			// aapt resource value: 0x7f080058
			public const int textViewLeadFuel4 = 2131230808;
			
			// aapt resource value: 0x7f080060
			public const int textViewLeadFuel5 = 2131230816;
			
			// aapt resource value: 0x7f08003f
			public const int textViewLeadName1 = 2131230783;
			
			// aapt resource value: 0x7f080047
			public const int textViewLeadName2 = 2131230791;
			
			// aapt resource value: 0x7f08004e
			public const int textViewLeadName3 = 2131230798;
			
			// aapt resource value: 0x7f080055
			public const int textViewLeadName4 = 2131230805;
			
			// aapt resource value: 0x7f08005d
			public const int textViewLeadName5 = 2131230813;
			
			// aapt resource value: 0x7f08003d
			public const int textViewLeadNum1 = 2131230781;
			
			// aapt resource value: 0x7f080045
			public const int textViewLeadNum2 = 2131230789;
			
			// aapt resource value: 0x7f08004c
			public const int textViewLeadNum3 = 2131230796;
			
			// aapt resource value: 0x7f080053
			public const int textViewLeadNum4 = 2131230803;
			
			// aapt resource value: 0x7f08005b
			public const int textViewLeadNum5 = 2131230811;
			
			// aapt resource value: 0x7f080040
			public const int textViewLeadPoint1 = 2131230784;
			
			// aapt resource value: 0x7f080048
			public const int textViewLeadPoint2 = 2131230792;
			
			// aapt resource value: 0x7f08004f
			public const int textViewLeadPoint3 = 2131230799;
			
			// aapt resource value: 0x7f080056
			public const int textViewLeadPoint4 = 2131230806;
			
			// aapt resource value: 0x7f08005e
			public const int textViewLeadPoint5 = 2131230814;
			
			// aapt resource value: 0x7f08007c
			public const int textViewLeaderboard = 2131230844;
			
			// aapt resource value: 0x7f08002d
			public const int textViewLiter = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int textViewLiterVal = 2131230766;
			
			// aapt resource value: 0x7f080010
			public const int textViewLocked1 = 2131230736;
			
			// aapt resource value: 0x7f080085
			public const int textViewLogout = 2131230853;
			
			// aapt resource value: 0x7f080089
			public const int textViewProfName = 2131230857;
			
			// aapt resource value: 0x7f080072
			public const int textViewProfile = 2131230834;
			
			// aapt resource value: 0x7f080082
			public const int textViewSettings = 2131230850;
			
			// aapt resource value: 0x7f080093
			public const int textViewStatus = 2131230867;
			
			// aapt resource value: 0x7f080098
			public const int textViewSuggestion = 2131230872;
			
			// aapt resource value: 0x7f08001b
			public const int textViewTabletNum = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int textViewTabletNumResult = 2131230748;
			
			// aapt resource value: 0x7f080005
			public const int textViewTitle = 2131230725;
			
			// aapt resource value: 0x7f080067
			public const int textView_fbtext = 2131230823;
			
			// aapt resource value: 0x7f08009f
			public const int userNameCheckResultTxtView = 2131230879;
			
			// aapt resource value: 0x7f08009e
			public const int username = 2131230878;
			
			// aapt resource value: 0x7f0800a8
			public const int vehicleTypeSpinner = 2131230888;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Awards = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Car = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Friends = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int History = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Home = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Leaderboard = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Profile = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Register = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Settings = 2130903050;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int loginErrorEnterPassword = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int loginErrorEnterUserName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int loginErrorLoginFailed = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int radio_female = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int radio_male = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int register_birthdate = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int register_carDetails = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int register_email = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int register_gender = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int register_lastname = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int register_name = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int register_password = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int register_password_repeat = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int register_personalDetails = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int register_plateNumber = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int register_uploadImage = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int register_username = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int register_vehicleType = 2131034125;
			
			// aapt resource value: 0x7f05001a
			public const int registrationFailed = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int registrationMandatoryFieldNull = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int registrationMsgUserNameAvailable = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int registrationMsgUserNameNotAvailable = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int registrationRetypePassword = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int registrationSuccessful = 2131034136;
			
			// aapt resource value: 0x7f050010
			public const int vehicle_prompt = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int wsCommunicationProblem = 2131034132;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int HomeFooter = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ThemeStandard = 2131165185;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
